name: unicorn
channels:
  - fvcore
  - iopath
  - pytorch
  - pytorch3d
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - fvcore=0.1.5.post20210518
  - gdown==4.4.0
  - imageio==2.8.0
  - imageio-ffmpeg==0.4.2
  - iopath=0.1.8
  - python=3.7.7
  - python-lmdb==1.3.0
  - pytorch=1.5.0
  - pytorch3d=0.4.0
  - pyyaml=5.3.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - torchvision=0.6.0
  - toolz=0.10.0
