dataset:
  name: comp_cars
  img_size: 64
model:
  name: unicorn
  mesh:
    init: ellipse
    scale: 0.6
    use_mean_txt: True
    deform_fields:
      powers: [2, 8, 32]
      milestones: [150, 300, 450]
    texture_uv:
      img_size: 64
      powers: [2, 8, 32, 128]
      milestones: [0, 150, 300, 450]
  background:
    powers: [4, 16, 64, 128]
    milestones: [0, 150, 300, 450]
  renderer:
    cameras:
      name: fov
      fov: 30
  rend_predictor:
    alternate_optim: True
    azim_range: [0, 360]
    elev_range: [-10, 30]
    roll_range: [-30, 30]
    T_range: [0.3, 0.3, 0.3]
    scale_range: [0.3, 0.3, 0.3]
  milestones:
    freeze_T_predictor: 2
    freeze_shape: 5
    freeze_scale_predictor: 50
  loss:
    name: mse
    rgb_weight: 1
    perceptual_weight: 10
    laplacian_weight: 0.01
    normal_weight: 0.01
    uniform_weight: 0.02
    swap_weight: 1
    swap_memsize: 1024
    swap_n_vpbins: 4
training:
  batch_size: 32
  n_workers: 4
  optimizer:
    name: adam
    lr: 1.0e-4
  n_epoches: 600
  save_epoches: [150, 300, 450]
  train_stat_interval: 2000
  val_stat_interval: 4000
  seed: 10939
  visualizer_port:
  resume:
